language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"

sudo: required

install:
  - sudo apt-get install -y lilv-utils calf-plugins guitarix --no-install-recommends

script:
  - pip install .
  - cd test
  - python test.py
