language: python

python:
  - "3.4"
  - "3.5"
  - "3.6-dev"
  - "nightly"

sudo: required

install:
  - pip3 install coveralls

script:
  - git clone https://github.com/PedalPi/Raspberry-P0.git --depth=1
  - cd Raspberry-P0
  - python setup.py develop
  - python test.py
